# https://www.linode.com/docs/guides/how-to-configure-load-balancing-with-tls-encryption-on-a-kubernetes-cluster/
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ts-htmlconverter-ns
---
apiVersion: v1
data:
  BasicAuth__Password: [Your Secret Text]
  BasicAuth__Username: [Your Secret Text]
kind: Secret
metadata:
  name: ts-htmlconverter-secr
  namespace: ts-htmlconverter-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-htmlconverter-app
  labels:
    app: ts-htmlconverter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ts-htmlconverter-app
  template:
    metadata:
      labels:
        app: ts-htmlconverter-app
      namespace: ts-htmlconverter-ns
    spec:
      containers:
      - name: htmlconverter
        image: townsuite/htmlconverterwebpi:latest
        env:
          - name: BasicAuth__Password
            valueFrom:
              secretKeyRef:
                key: BasicAuth__Password
                name: ts-htmlconverter-secr
          - name: BasicAuth__Username
            valueFrom:
              secretKeyRef:
                key: BasicAuth__Username
                name: ts-htmlconverter-secr
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
      #imagePullSecrets:
      #- name: [Your Secrets Name]
---
apiVersion: v1
kind: Service
metadata:
  name: ts-htmlconverter-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ts-htmlconverter-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - [Add your url here]
    secretName: letsencrypt-secret-prod
  rules:
  - host: [Add your url here]
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ts-htmlconverter-service
            port:
              number: 80

